### ISSUE TITLE
BearerTokenAccessDeniedHandler duplicates code from BearerTokenAuthenticationEntryPoint

### ISSUE THREAD

**Issue by jgrandja** [jzheaux/spring-security#15]
Bringing over the discussion from my feedback comment in the commit earlier this week.

**Joe:**

`BearerTokenAccessDeniedHandler` has the same code as `BearerTokenAuthenticationEntryPoint`.

Moreover, `BearerTokenAccessDeniedHandler` responds with a 403 forbidden status but with the `WWW-Authenticate`, which is not correct. `WWW-Authenticate` header should have a 401 status.

I don't see why we need `BearerTokenAccessDeniedHandler`?

**Josh:**

We need `BearerTokenAccessDeniedHandler` for when access is denied either by filter security or method security. In either case, without a specialized `AccessDeniedHandler`, when a bearer token does not have sufficient scope, we will simply return a 403, which would depart from the spec.

What I'm looking at is https://tools.ietf.org/html/rfc6750#section-3.1 where it states:

```
insufficient_scope
         The request requires higher privileges than provided by the
         access token.  The resource server SHOULD respond with the HTTP
         403 (Forbidden) status code and MAY include the "scope"
         attribute with the scope necessary to access the protected
         resource.
```

Also, semantically, I've always seen access denied as 403 which seems to be what `AccessDeniedHandlerImpl` also defaults to. Where do you read that `WWW-Authenticate` should be 401? Is this in conflict with the above-quoted spec language?

**Comment by jgrandja** [comment]
Related #14, #12

**Comment by jgrandja** [comment]
> Also, semantically, I've always seen access denied as 403 which seems to be what AccessDeniedHandlerImpl also defaults to. Where do you read that `WWW-Authenticate` should be 401?

HTTP Status 401 is returned when the current request lacks credentials or is unauthenticated. The server responds with 401 Unauthorized and an authentication  challenge.

HTTP Status 403 is returned when the current has valid credentials or is authenticated but lacks the permission to access the protected resource - 403 Forbidden.

`WWW-Authenticate` is only returned when the request lacks authentication information. It is never returned with a 403 because the request is already authenticated but doesn't have required access rights. This is standard HTTP spec.

**Comment by jzheaux** [comment]
@jgrandja Quick clarification

My reading of the OAuth spec says that a WWW-Authenticate header and status code 403 need to be returned when returning insufficient_scope:

> If the protected resource request does not include authentication
   credentials or does not contain an access token that enables access
   to the protected resource, the resource server MUST include the HTTP
   "WWW-Authenticate" response header field
    ....
    If the protected resource request included an access token and failed
   authentication, the resource server SHOULD include the "error"
   attribute to provide the client with the reason why the access
   request was declined.  The parameter value is described in
   Section 3.1.
    ....
    insufficient_scope
        The request requires higher privileges than provided by the
        access token.  The resource server SHOULD respond with the HTTP
        403 (Forbidden) status code and MAY include the "scope"
        attribute with the scope necessary to access the protected
        resource.

Have I pieced these together incorrectly?

**Comment by jgrandja** [comment]
> My reading of the OAuth spec says that a WWW-Authenticate header and status code 403 need to be returned when returning insufficient_scope

Where exactly in the spec does it state that....**WWW-Authenticate header and status code 403 need to be returned...**

I don't see it anywhere.

**Comment by jzheaux** [comment]
In what header would you send back `error_code=insufficient_scope` otherwise?

**Comment by jzheaux** [comment]
@jgrandja, based on yours and my further analysis of the spec, I believe that the code is already compliant.

That said, I did take your comment about code duplication to heart and, for now, I have taken the relevant parts of BearerTokenErrorUtils and moved them into the entry point and the denial handler, just so fewer things are public for this first PR. Thanks for the recommendation.
