### ISSUE TITLE
Jar name and packaging

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security#2]
### Summary
I'm not sure I like the discrepancy between the name of the jar and the package name. Currently there is a `-` between `resource` and `server` which would imply that the there is a `.` between the package name.

I am currently thinking that a jar name of `spring-security-oauth2-server-resource` and base package of `org.springframework.security.oauth2.server.resource` would be preferable. This has some benefits:
* Consistency with the `-` and `.` usage
* The authorization server jar would be named `spring-security-oauth2-server-authorization` and a package of `org.springframework.security.oauth2.server.authorization`. This means that all server code shares the same base package of  `org.springframework.security.oauth2.server`
* It aligns all server code nicely with `org.springframework.security.oauth2.client`

Thoughts?

NOTE: The disadvantage is that we use `server` package for reactive code which would mean `server` is in the package name twice.

cc @jgrandja @jzheaux

**Comment by jzheaux** [comment]
>  The disadvantage is that we use server package for reactive code which would mean server is in the package name twice.

This is why we originally went with `resourceserver` for the package name. You can see the conversation here:

https://github.com/jzheaux/spring-security-oauth2-resource-server/issues/1

**Comment by rwinch** [comment]
This isn't the exact same though. There would not be collisions with my naming suggestion. Just a package name with server twice in it.

I don't agree with keeping resourceserver and authorizationserver at the same level. They are both server sides of the protocol so it makes sense for a shared parent package of server. This is nice for things like logging (can enable logging for all server side components with a single statement).

In regards to nothing in the the server package, this is not an issue. There are plenty of packages that are for organization and nothing more. A few examples of packages with no classes in it are `org.springframework`, `org.springframework.mock.web.reactive`, `org.springframework.context.annotation`, `org.springframework.security.access.intercept`, `org.springframework.security.web.reactive`.

I still think this is a good idea structurally to share a common package structure for OAuth server related components.

**Comment by jgrandja** [comment]
So the current structure is this:

```
org.springframework.security.oauth2.resourceserver
org.springframework.security.oauth2.authorizationserver
```

The proposed structure is this:

```
org.springframework.security.oauth2.server.resource
org.springframework.security.oauth2.server.authorization
```

I originally recommended this structure as well and I'm leaning back to it as it does reads better IMO and @rwinch made some good points/benefits to this structure. Also, after deciding to go with the current structure, there have been a few times where I just felt `resourceserver` and the upcoming `authorizationserver` sub-package naming is too long for my liking.

@rwinch Other than `server` being repeated twice for the Reactive bits, do you foresee any other issues that may arise when building out the Reactive end of things?

I also think that no code under the `org.springframework.security.oauth2.server` package is fine. It's main goal is to organize which is a good  thing.

**Comment by rwinch** [comment]
> Other than server being repeated twice for the Reactive bits, do you foresee any other issues that may arise when building out the Reactive end of things?

That is the only disadvantage to the package structure I can think of at the moment.

As for the jar names it might be difficult for users to remember that server is first when adding dependencies.

**Comment by jzheaux** [comment]
I'm not convinced by the length argument as typing "server.resource" is just as long as typing "resourceserver". Are there other reasons why length is a problem (so long as its meaning is clear)? While I can appreciate that every person has their own internal length threshold when something starts to "feel" long, it isn't triggered for me with `authorizationserver`, so I'll need some more help to see why length is an issue.

Agreed that there should be alignment between dashes and dots. If the package structure stays as it is, the project name should be corrected.

I do like the idea of being able to isolate server logs. Is having RS and AS deployed together a common use case with legacy oauth?

And, I also do see the value of additional structure for its own sake, and if the OAuth2 domain language weren't "server", I'd be more inclined towards a separation.

My concern with `org.springframework.security.oauth2.server.resource.server` is the semantic collision (though I'm happy to hear that there is no physical collision in the directory structure). Personally, I like o.s.s.o.**rs**.server over both `server.resource.server` and `resourceserver.server`. The project name would be `spring-security-oauth2-rs` which lines up with other common abbreviations like `ldap` and `crypto`.

(I think folks would expect a package called `org.springframework.security.saml.idp` as opposed to `org.springframework.security.saml.server.identity`. Though to that point, if there is alignment we can achieve between the saml projects and the oauth projects, I'd be in favor of that as I think consistency would beat out both concerns at that point.)

Disregarding that as an option, though, I see `resourceserver.server` as slightly better than `server.resource.server` in that `spring-security-oauth2-resourceserver` I think is a more reasonable project name than `spring-security-oauth2-server-resource` (unfortunately the word "server" can be interpreted as a modifier here (read: "a resource used by a server"), adding to potential (though still minor) confusion).

Do the structural benefits of `server.resource` outweigh the semantic benefits of `resourceserver` (or `rs`)? I favor semantics very slightly over structure, but I feel like a whole bunch of left-brained engineers can figure it out either way. =]

**Comment by rwinch** [comment]
> I'm not convinced by the length argument as typing "server.resource" is just as long as typing "resourceserver". Are there other reasons why length is a problem (so long as its meaning is clear)? 

The problem I have with resourceserver is it is multiple words in a package name. This is not something that is very conventional. What's more it makes it more difficult to read because there is no separator or camel case to help distinguish the words.

> I do like the idea of being able to isolate server logs. Is having RS and AS deployed together a common use case with legacy oauth?

In the new codebase authorization server will use resource server code to protect its endpoints. So it will be quite common.

> My concern with org.springframework.security.oauth2.server.resource.server

It will be org.springframework.security.oauth2.server.resource.web.server

> Personally, I like o.s.s.o.rs.server

Using `rs` breaks both Spring and Java conventions. Spring favors readability over using short names. This is a general statement of the java world. I strongly disagree with using `rs` as a package name to save some typing. Very few users type package names (their IDE does it for them).

I really cannot buy into a package name that has two words in it. Breaking a precedent like this is not a good idea.

**Comment by jzheaux** [comment]
(Thank you for the correction on the projected reactive package name)

> Using rs breaks both Spring and Java conventions

What conventions are you referring to? I'm not trying to be contrary, but we do `http`, `xml`, `jwt`, `jwk` and many other conventional abbreviations in package names.

I would agree that is it a little chancier to say "Hey, let me tell you about this RS I just stood up that supports JWTs" and expect that I'd be understood vs just saying "resource server" in full. (heck, I said " login in with your u/p" for years before I got tired of people saying "my what?"--I guess some abbreviations don't stick)

`rs` is definitely not as conventional as, say, `sp` or `idp` in the saml world, but I see them as semantically related.  What are your thoughts so far on what packages will look like in `spring-security-saml`? If you think we should do `server.identity` over `idp`, then I'm all over `server.resource`.

> I strongly disagree with using rs as a package name to save some typing. 

Agreed. What I'm looking for is semantic clarity, not less typing (as you see from my first point about not having a personal problem with `authorizationserver` or `resourceserver`). If `rs` is not yet conventional enough then my second vote is `resourceserver`.

To be clear, I'm not interested in stumping any harder for any approach (except for maybe saml-oauth consistency if it applies) as I think the tradeoffs are minor. If I'm outvoted, I won't lose sleep over it.

**Comment by rwinch** [comment]
> What conventions are you referring to? I'm not trying to be contrary, but we do http, xml, jwt, jwk and many other conventional abbreviations in package names.

These are well known acronyms that if they were brought up in conversation with a software engineer they would be easily recognized. Do you consider `rs` a well known acronym (I don't)? Where does Spring use the first letter of multiple words to form a package name?

> springframework

This is quite a bit different. The package prefix of org.springframework comes from the domain that was owned by Spring and thus it follows package naming conventions.

**Comment by jzheaux** [comment]
All fair points. I simply don't see `resourceserver` as an egregious misstep, and I think that it is clearer than `server.resource`. I think the project names turn out better this way, too. I understand that `rs` is a hard sell insofar as it is not yet a conventional acronym. I don't see `server.resource` as so bad that I'm inclined to push any further for either alternative, though.

>  Do you consider rs a well known acronym (I don't)? Where does Spring use the first letter of multiple words to form a package name?

I think I've already made my position clear here, but just in case, the answers are "no" and "nowhere that I know of, though since this isn't really my point, I didn't take the time to look".

**Comment by jgrandja** [comment]
Although I'm leaning towards:

```
org.springframework.security.oauth2.server.resource
org.springframework.security.oauth2.server.authorization
```

I'm not a fan of:

```
spring-security-oauth2-server-resource
spring-security-oauth2-server-authorization
```

Much more prefer:

```
spring-security-oauth2-resource-server
spring-security-oauth2-authorization-server
```

But than the package structure and project/jar don't align.

This is a tough one no doubt but good thing we're trying to figure it out now.

I'm not a fan or `rs` or `as` so let's move on from that.

**Comment by rwinch** [comment]
Jar names and packages don't always align. So we could stick with the jar name that makes more sense.

**Comment by jzheaux** [comment]
I do like `spring-security-oauth2-resource-server` much more than `spring-security-oauth2-server-resource`. I think that it reads more cleanly and is easier to remember.

I'm not 100% comfortable with having the package and project misaligned, but perhaps that is less important since one they will type out and the other they will not. Is this the first Spring Security project with a two-word subject (read: looking for precedent)? 

I'll mention for completeness that I would vote "no" on:

```
org.springframework.security.oauth2.resource.server
org.springframework.security.oauth2.authorization.server
```

If we are going to split them up, we need to gain the structural benefits from doing so.

**Comment by rwinch** [comment]
My current proposal is:

org.springframework.security.oauth2.server.resource
org.springframework.security.oauth2.server.authorization

and jar names

spring-security-oauth2-resource-server
spring-security-oauth2-authorization-server
